/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author andra
 */
public class Dashbord extends javax.swing.JFrame {

    /**
     * Creates new form Dashbord
     */
    public Dashbord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JButton();
        reg = new javax.swing.JButton();
        pbuku = new javax.swing.JButton();
        imhs = new javax.swing.JButton();
        ibuku = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        logout.setBackground(new java.awt.Color(102, 0, 0));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/icon/log out.png"))); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(950, 620, 146, 52);

        reg.setBackground(new java.awt.Color(204, 204, 204));
        reg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/icon/registration.png"))); // NOI18N
        reg.setText("REGISTER");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        getContentPane().add(reg);
        reg.setBounds(0, 620, 146, 52);

        pbuku.setBackground(new java.awt.Color(127, 144, 147));
        pbuku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pbuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/icon/pinjam buku.png"))); // NOI18N
        pbuku.setText("PEMINJAMAN PENGEMBLIAN");
        pbuku.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbukuActionPerformed(evt);
            }
        });
        getContentPane().add(pbuku);
        pbuku.setBounds(730, 300, 290, 190);

        imhs.setBackground(new java.awt.Color(127, 144, 147));
        imhs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        imhs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/icon/people.png"))); // NOI18N
        imhs.setText("INPUT MAHASISWA");
        imhs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imhsActionPerformed(evt);
            }
        });
        getContentPane().add(imhs);
        imhs.setBounds(120, 300, 290, 190);

        ibuku.setBackground(new java.awt.Color(127, 144, 147));
        ibuku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ibuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/icon/book.png"))); // NOI18N
        ibuku.setText("INPUT DATA BUKU");
        ibuku.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ibuku.setMargin(new java.awt.Insets(0, 14, 2, 14));
        ibuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibukuActionPerformed(evt);
            }
        });
        getContentPane().add(ibuku);
        ibuku.setBounds(420, 300, 290, 190);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/backgound/backgroundregister.png"))); // NOI18N
        jLabel13.setMaximumSize(new java.awt.Dimension(1090, 670));
        jLabel13.setMinimumSize(new java.awt.Dimension(1090, 670));
        jLabel13.setPreferredSize(new java.awt.Dimension(1090, 670));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1090, 670);

        setBounds(0, 0, 1108, 707);
    }// </editor-fold>//GEN-END:initComponents

    private void ibukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibukuActionPerformed
        // TODO add your handling code here:
        FrameInput frame = new FrameInput();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ibukuActionPerformed

    private void pbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbukuActionPerformed
        // TODO add your handling code here:
        PinjamBuku frame = new PinjamBuku();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pbukuActionPerformed

    private void imhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imhsActionPerformed
        // TODO add your handling code here:
        FrameMahasiswa frame = new FrameMahasiswa();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imhsActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        // TODO add your handling code here:
        FrameRegister frame = new FrameRegister();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        FrameLogin frame = new FrameLogin();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashbord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ibuku;
    private javax.swing.JButton imhs;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JButton logout;
    private javax.swing.JButton pbuku;
    private javax.swing.JButton reg;
    // End of variables declaration//GEN-END:variables
}
